name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
    - uses: actions/checkout@v3

    - name: Generate builds
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'linux/amd64, windows/amd64'
        package: './cmd/app'
        name: 'nsgpeek'
        compress: 'true'
        dest: 'dist'

